### PR TITLE
Add Norwegian translations

### PR DESCRIPTION
**Pull request by Z0ink5**
Translated by me

### CODE REVIEW

**Comment by Z0ink5** [comment]
Not sure why it failed, let me know if there's something I can fix in my pull request. :-)

**Comment by samuelmeuli** [comment]
There are some linting errors. Running `yarn lint:css:fix && yarn lint:ts:fix && yarn format:fix` should fix them for you. You can then commit the changes and push them to this PR's branch (`master` in your case), which will update the PR. No need to create a new one ;)

**Comment by Z0ink5** [comment]
> There are some linting errors. Running `yarn lint:css:fix && yarn lint:ts:fix && yarn format:fix` should fix them for you. You can then commit the changes and push them to this PR's branch (`master` in your case), which will update the PR. No need to create a new one ;)

Thanks for that - I tried doing this in command line (running Windows 10 here) but I keep getting some errors about not matching any files etc. In which folder should I run this command? I used it on my clone of the Github-project itself.

New to pushing/pulling etc. :)   

Img of output here:    https://prnt.sc/saahps

**Comment by samuelmeuli** [comment]
Looks like Windows [doesn't like single quotes](https://stackoverflow.com/a/48104731/6767508) in NPM scripts... I'll fix it on my machine :)

**Comment by samuelmeuli** [comment]
Thanks a lot for contributing! :)

**Pull request merged**
