### PR TITLE
Added pt-br translation.

### PR DESCRIPTION
**Pull request by lincolncosta**

### CODE REVIEW

**Comment by samuelmeuli** [comment]
Hey @tekpixo, thanks a lot for the PR!

Could these translations be applied to the `pt` locale in general, or are there significant differences between `pt-BR` and `pt-PR`?

Also, I've realized that I forgot to mark a few strings for localization. Would you mind adding Portuguese translations for [these](https://github.com/samuelmeuli/mini-diary/commit/26346e7775db381a7c31aef0238c344ecc9efeec) and [this one](https://github.com/samuelmeuli/mini-diary/commit/def90e0d5d0f49c1ca2a66144b4911e0d40045a6) as well? :)

**Comment by lincolncosta** [comment]
Hi @samuelmeuli!

I know there are some differences between brazilian portuguese and european portuguese but I'm not sure about how significant the differences can be, if you don't mind I can apply it to `pt` in general, it's up to you.

Make your decision about `pt-PT` or `pt-BR`, then I will do all the changes you need on the others strings.

**Comment by samuelmeuli** [comment]
Let's assign the translations to `pt` for now, this makes it easier to maintain them.

**Comment by lincolncosta** [comment]
Hey @samuelmeuli, I've done the changes, take a look on it.

**Comment by samuelmeuli** [comment]
Awesome, thanks a lot!

Could you please remove the changes to the `.gitignore` file, and I'll merge the PR :)

**Comment by lincolncosta** [comment]
@samuelmeuli done!

If you need anything else, feel free to ask. I'll be looking for another issue to resolve.

**Pull request merged**
